"""Authentication module — invite-based signup, session tokens, admin roles.

Design:
  - Passwords hashed with PBKDF2-HMAC-SHA256 (stdlib only, no external deps)
  - Session tokens are random 32-byte URL-safe strings
  - Invite codes: one-time use, generated by admin only
  - Admin: beulajoshua8@gmail.com (auto-created on first run)
  - All credentials stored in SQLite (data/judah.db)

No external dependencies — uses only hashlib, secrets, hmac, base64.
"""

from __future__ import annotations

import hashlib
import hmac
import logging
import os
import secrets
import base64
import time
from datetime import datetime, timezone
from typing import Optional

from backend.db import _PooledConn

logger = logging.getLogger("judah.auth")

# ── Constants ────────────────────────────────────────────────────

_SALT_LENGTH = 16          # PBKDF2 salt bytes
_HASH_LENGTH = 32          # SHA-256 output bytes
_PBKDF2_ITERATIONS = 100_000
_TOKEN_BYTES = 32          # Session token entropy
_TOKEN_TTL_SEC = 7 * 86400  # 7 days
_INVITE_TTL_SEC = 86400    # 1 day for unused invites
_INVITE_CODE_LENGTH = 12   # Characters in invite code


# ── Schema ───────────────────────────────────────────────────────

_AUTH_SCHEMA = """
-- Users table
CREATE TABLE IF NOT EXISTS auth_users (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    email       TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    salt        TEXT NOT NULL,
    role        TEXT NOT NULL DEFAULT 'user',  -- 'admin' | 'user'
    is_active   INTEGER NOT NULL DEFAULT 1,
    created_at  TEXT NOT NULL DEFAULT (datetime('now')),
    last_login  TEXT
);

-- Invite codes (one-time use)
CREATE TABLE IF NOT EXISTS auth_invites (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    code        TEXT UNIQUE NOT NULL,
    email       TEXT,            -- Optional: bound to specific email
    created_by  TEXT NOT NULL,   -- Admin email
    used_by     TEXT,            -- Email that used it
    used_at     TEXT,
    expires_at  TEXT NOT NULL,
    created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Active sessions (token -> user mapping)
CREATE TABLE IF NOT EXISTS auth_sessions (
    token       TEXT PRIMARY KEY,
    user_id     INTEGER NOT NULL,
    email       TEXT NOT NULL,
    role        TEXT NOT NULL,
    created_at  TEXT NOT NULL,
    expires_at  TEXT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES auth_users(id)
);

CREATE INDEX IF NOT EXISTS idx_sessions_token ON auth_sessions(token);
CREATE INDEX IF NOT EXISTS idx_sessions_user  ON auth_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_invites_code   ON auth_invites(code);
"""


# ── Password hashing (stdlib only) ──────────────────────────────

def _hash_password(password: str, salt: Optional[bytes] = None) -> tuple[str, str]:
    """Hash a password with PBKDF2-HMAC-SHA256.

    Returns (salt_b64, hash_b64) — both base64-encoded for storage.
    """
    if salt is None:
        salt = secrets.token_bytes(_SALT_LENGTH)
    pw_hash = hashlib.pbkdf2_hmac(
        "sha256",
        password.encode("utf-8"),
        salt,
        _PBKDF2_ITERATIONS,
        dklen=_HASH_LENGTH,
    )
    return base64.b64encode(salt).decode(), base64.b64encode(pw_hash).decode()


def _verify_password(password: str, salt_b64: str, hash_b64: str) -> bool:
    """Verify a password against stored hash."""
    salt = base64.b64decode(salt_b64)
    new_hash = hashlib.pbkdf2_hmac(
        "sha256",
        password.encode("utf-8"),
        salt,
        _PBKDF2_ITERATIONS,
        dklen=_HASH_LENGTH,
    )
    return hmac.compare_digest(
        base64.b64encode(new_hash).decode(),
        hash_b64,
    )


# ── Token management ─────────────────────────────────────────────

def _create_token() -> str:
    """Generate a cryptographically random session token."""
    return secrets.token_urlsafe(_TOKEN_BYTES)


async def _create_session(user_id: int, email: str, role: str) -> str:
    """Create a session for a user, return the token."""
    token = _create_token()
    now = datetime.now(timezone.utc)
    expires = datetime.fromtimestamp(now.timestamp() + _TOKEN_TTL_SEC, tz=timezone.utc)

    async with _PooledConn() as conn:
        await conn.execute(
            "INSERT INTO auth_sessions (token, user_id, email, role, created_at, expires_at) "
            "VALUES (?, ?, ?, ?, ?, ?)",
            (token, user_id, email, role, now.isoformat(), expires.isoformat()),
        )
        await conn.commit()
    return token


async def validate_token(token: str) -> Optional[dict]:
    """Validate a session token, return user info or None."""
    try:
        async with _PooledConn() as conn:
            cur = await conn.execute(
                "SELECT s.user_id, s.email, s.role, s.expires_at, u.is_active "
                "FROM auth_sessions s "
                "JOIN auth_users u ON u.id = s.user_id "
                "WHERE s.token = ?",
                (token,),
            )
            row = await cur.fetchone()
        if row is None:
            return None
        if row["is_active"] == 0:
            return None
        if datetime.fromisoformat(row["expires_at"]) < datetime.now(timezone.utc):
            # Expired — clean up
            async with _PooledConn() as conn:
                await conn.execute("DELETE FROM auth_sessions WHERE token = ?", (token,))
                await conn.commit()
            return None
        return {"user_id": row["user_id"], "email": row["email"], "role": row["role"]}
    except Exception:
        return None


async def revoke_token(token: str) -> None:
    """Invalidate a session token."""
    try:
        async with _PooledConn() as conn:
            await conn.execute("DELETE FROM auth_sessions WHERE token = ?", (token,))
            await conn.commit()
    except Exception:
        pass


# ── User management ──────────────────────────────────────────────

async def create_user(email: str, password: str, role: str = "user") -> dict:
    """Create a new user. Returns user dict or raises ValueError."""
    email = email.strip().lower()
    if not email or "@" not in email:
        raise ValueError("Invalid email address")
    if not password or len(password) < 6:
        raise ValueError("Password must be at least 6 characters")

    salt_b64, hash_b64 = _hash_password(password)

    try:
        async with _PooledConn() as conn:
            cur = await conn.execute(
                "INSERT INTO auth_users (email, password_hash, salt, role) VALUES (?, ?, ?, ?)",
                (email, hash_b64, salt_b64, role),
            )
            user_id = cur.lastrowid
            await conn.commit()
        logger.info("[auth] Created user: %s (role=%s)", email, role)
        return {"user_id": user_id, "email": email, "role": role}
    except Exception as e:
        if "UNIQUE constraint" in str(e) or "unique" in str(e).lower():
            raise ValueError("Email already registered")
        raise


async def authenticate(email: str, password: str) -> Optional[dict]:
    """Authenticate a user. Returns user dict or None."""
    email = email.strip().lower()
    try:
        async with _PooledConn() as conn:
            cur = await conn.execute(
                "SELECT id, password_hash, salt, role, is_active FROM auth_users WHERE email = ?",
                (email,),
            )
            row = await cur.fetchone()
        if row is None:
            return None
        if row["is_active"] == 0:
            return None
        if not _verify_password(password, row["salt"], row["password_hash"]):
            return None
        # Update last_login
        async with _PooledConn() as conn:
            await conn.execute(
                "UPDATE auth_users SET last_login = ? WHERE id = ?",
                (datetime.now(timezone.utc).isoformat(), row["id"]),
            )
            await conn.commit()
        return {"user_id": row["id"], "email": email, "role": row["role"]}
    except Exception:
        return None


async def get_user_by_email(email: str) -> Optional[dict]:
    """Get user by email."""
    email = email.strip().lower()
    try:
        async with _PooledConn() as conn:
            cur = await conn.execute(
                "SELECT id, email, role, is_active, created_at, last_login FROM auth_users WHERE email = ?",
                (email,),
            )
            row = await cur.fetchone()
        if row:
            return dict(row)
        return None
    except Exception:
        return None


async def list_users() -> list[dict]:
    """List all users (admin only)."""
    try:
        async with _PooledConn() as conn:
            cur = await conn.execute(
                "SELECT id, email, role, is_active, created_at, last_login FROM auth_users"
            )
            rows = await cur.fetchall()
        return [dict(r) for r in rows]
    except Exception:
        return []


async def deactivate_user(user_id: int) -> bool:
    """Deactivate a user account."""
    try:
        async with _PooledConn() as conn:
            await conn.execute(
                "UPDATE auth_users SET is_active = 0 WHERE id = ?",
                (user_id,),
            )
            # Also revoke all their sessions
            await conn.execute(
                "DELETE FROM auth_sessions WHERE user_id = ?",
                (user_id,),
            )
            await conn.commit()
        return True
    except Exception:
        return False


# ── Invite codes ─────────────────────────────────────────────────

async def create_invite(admin_email: str, bound_email: Optional[str] = None) -> dict:
    """Generate a one-time invite code. Admin only.

    Args:
        admin_email: Email of the admin creating the invite.
        bound_email: Optional — restrict invite to this specific email.
    """
    code = secrets.token_urlsafe(_INVITE_CODE_LENGTH)
    now = datetime.now(timezone.utc)
    expires = datetime.fromtimestamp(now.timestamp() + _INVITE_TTL_SEC, tz=timezone.utc)

    try:
        async with _PooledConn() as conn:
            await conn.execute(
                "INSERT INTO auth_invites (code, email, created_by, expires_at) VALUES (?, ?, ?, ?)",
                (code, bound_email, admin_email, expires.isoformat()),
            )
            await conn.commit()
        logger.info("[auth] Invite created by %s for %s", admin_email, bound_email or "any")
        return {"code": code, "expires_at": expires.isoformat(), "email": bound_email}
    except Exception as e:
        raise ValueError(f"Failed to create invite: {e}")


async def validate_invite(code: str, email: str) -> bool:
    """Validate and consume an invite code. Returns True if valid."""
    email = email.strip().lower()
    try:
        async with _PooledConn() as conn:
            cur = await conn.execute(
                "SELECT id, email, used_by, expires_at FROM auth_invites WHERE code = ?",
                (code,),
            )
            row = await cur.fetchone()
        if row is None:
            return False
        # Check if already used
        if row["used_by"] is not None:
            return False
        # Check if expired
        if datetime.fromisoformat(row["expires_at"]) < datetime.now(timezone.utc):
            return False
        # Check email binding
        if row["email"] and row["email"].lower() != email:
            return False
        # Mark as used
        async with _PooledConn() as conn:
            await conn.execute(
                "UPDATE auth_invites SET used_by = ?, used_at = ? WHERE id = ?",
                (email, datetime.now(timezone.utc).isoformat(), row["id"]),
            )
            await conn.commit()
        return True
    except Exception:
        return False


async def list_invites() -> list[dict]:
    """List all invite codes (admin only)."""
    try:
        async with _PooledConn() as conn:
            cur = await conn.execute(
                "SELECT id, code, email, created_by, used_by, used_at, expires_at, created_at "
                "FROM auth_invites ORDER BY created_at DESC"
            )
            rows = await cur.fetchall()
        return [dict(r) for r in rows]
    except Exception:
        return []


# ── Bootstrap ────────────────────────────────────────────────────

async def ensure_bootstrap() -> None:
    """Ensure the auth schema exists and create admin user if needed.

    Admin: beulajoshua8@gmail.com
    Password: set via environment variable AUTH_ADMIN_PASSWORD or auto-generated.
    """
    try:
        async with _PooledConn() as conn:
            await conn.executescript(_AUTH_SCHEMA)
            await conn.commit()
    except Exception:
        pass

    # Check if admin exists
    admin = await get_user_by_email("beulajoshua8@gmail.com")
    if admin:
        return

    # Create admin user with env password or auto-generated
    admin_password = os.environ.get("AUTH_ADMIN_PASSWORD")
    if not admin_password:
        admin_password = secrets.token_urlsafe(16)
        logger.warning("[auth] No AUTH_ADMIN_PASSWORD env var — admin password auto-generated: %s", admin_password)

    await create_user("beulajoshua8@gmail.com", admin_password, role="admin")
    logger.info("[auth] Admin user created: beulajoshua8@gmail.com")


# ── Session cleanup (stale tokens) ───────────────────────────────

async def prune_old_sessions(older_than_hours: int = 168) -> int:
    """Remove expired sessions. Returns count removed."""
    try:
        cutoff = datetime.fromtimestamp(
            time.time() - older_than_hours * 3600, tz=timezone.utc
        ).isoformat()
        async with _PooledConn() as conn:
            cur = await conn.execute(
                "DELETE FROM auth_sessions WHERE expires_at < ?", (cutoff,)
            )
            count = cur.rowcount
            await conn.commit()
        if count > 0:
            logger.debug("[auth] Pruned %d expired sessions", count)
        return count
    except Exception:
        return 0
